name: Python Tests and Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # check PEP8 compliance
        flake8 . --count --max-line-length=100 --statistics --extend-ignore=E203
        # run full report with all warnings
        flake8 . --count --max-complexity=10 --max-line-length=100 --statistics --format=html --htmldir=flake-report
    
    - name: Test with pytest
      run: |
        pytest testing/ --html=report.html --self-contained-html
    
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html

    - name: Upload PEP8 report
      uses: actions/upload-artifact@v4
      with:
        name: pep8-report
        path: flake-report/